## 들여쓰기와 공백을 준수하세요
defaults:
  - model: freqnet       
  - optimizer: adam
  - scheduler: cosine
  - criterion: cross_entropy
  - data: data
  - _self_               

seed: 42

exp_name: "baseline"  # 실험명: baseline, augmentation, architecture_test 등

wandb:
  project_name: "MIP-0"
  entity: 'dmachine-kyung-hee-university'

checkpoint:
  save_dir: "/content/drive/MyDrive/Models/checkpoints"  # 구글 드라이브 경로

run:
  epochs: 20
  early_stopping:
    enabled: True
    patience: 3